/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamsRouteImport } from './routes/teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backtesting': typeof BacktestingRoute
  '/competitions': typeof CompetitionsRoute
  '/odds': typeof OddsRoute
  '/performance': typeof PerformanceRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backtesting': typeof BacktestingRoute
  '/competitions': typeof CompetitionsRoute
  '/odds': typeof OddsRoute
  '/performance': typeof PerformanceRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backtesting': typeof BacktestingRoute
  '/competitions': typeof CompetitionsRoute
  '/odds': typeof OddsRoute
  '/performance': typeof PerformanceRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/backtesting'
    | '/competitions'
    | '/odds'
    | '/performance'
    | '/rankings'
    | '/settings'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/backtesting'
    | '/competitions'
    | '/odds'
    | '/performance'
    | '/rankings'
    | '/settings'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/backtesting'
    | '/competitions'
    | '/odds'
    | '/performance'
    | '/rankings'
    | '/settings'
    | '/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BacktestingRoute: typeof BacktestingRoute
  CompetitionsRoute: typeof CompetitionsRoute
  OddsRoute: typeof OddsRoute
  PerformanceRoute: typeof PerformanceRoute
  RankingsRoute: typeof RankingsRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BacktestingRoute: BacktestingRoute,
  CompetitionsRoute: CompetitionsRoute,
  OddsRoute: OddsRoute,
  PerformanceRoute: PerformanceRoute,
  RankingsRoute: RankingsRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
